feat: new maproxy
MapColonies/mapproxy pull request #1
Opened 2023-08-09 08:06 UTC by asafMasa

2023-08-21 07:14 UTC, CL-SHLOMIKONCHA requested changes

2023-08-29 08:11 UTC, asafMasa reviewed
please mind my comments

2023-08-29 08:11 UTC, asafMasa commented on helm/templates/mapproxy-configmap.yaml
> +  AUTH_ENABLED: {{ .Values.mapproxy.env.authentication.WMS.enabled | quote }}
was WMS AUTH usage removed from mapproxy, if so was it handled in NGINX level?

2023-08-29 08:11 UTC, asafMasa commented on helm/templates/mapproxy-configmap.yaml
> +  CORS_ALLOWED_HEADERS: {{ template "map-proxy.cors.allowedHeaders" . }}
was CORS usage removed from mapproxy, if so was it handled in NGINX level?

2023-08-29 08:11 UTC, asafMasa commented on helm/templates/mapproxy-configmap.yaml
> +  TELEMETRY_TRACING_ENABLED: {{ .Values.global.tracing.enabled | quote }}
where is TELEMETRY_Metrics_ENABLED ?

2023-08-29 08:11 UTC, asafMasa commented on helm/templates/mapproxy-configmap.yaml
> +  TELEMETRY_TRACING_ENABLED: {{ .Values.global.tracing.enabled | quote }}
where is Tracing sampling ratio ?

2023-09-04 08:15 UTC, vitaligi commented on config/uwsgi/uwsgi.default.conf
> +log-format = {"timestamp": "%(timestamp)", "source": "uwsgi", "type": "request", "status": %(status), "method": "%(method)", "path": "%(uri)", "user_agent": "%(uagent)", "duration_in_ms": %(msecs), "
the missing quotes are for numeric attributes

2023-09-04 08:15 UTC, vitaligi commented on helm/templates/mapproxinator-container.yaml
> +            - name: REQUESTS_CA_BUNDLE
removed

2023-09-04 08:15 UTC, vitaligi commented on helm/templates/mapproxy-container.yaml
> +            - name: REQUESTS_CA_BUNDLE
removed

2023-09-04 08:16 UTC, vitaligi commented on .dockerignore
> +**/npm-debug.log
removed

2023-09-04 08:16 UTC, vitaligi commented on .dockerignore
> +**/node_modules
removed

2023-09-04 10:43 UTC, vitaligi commented on helm/templates/mapproxy-init-container.yaml
> +            - name: REQUESTS_CA_BUNDLE
moved and changed the if statement

2023-09-04 10:45 UTC, vitaligi commented on requirements.txt
> +protobuf==3.17.3
added boto3. botocore is already inside. why redis?

2023-09-04 10:54 UTC, vitaligi commented on .github/workflows/snyk.xml
> +name: snyk
@AnguIar is this needed?

2023-09-06 07:33 UTC, vitaligi commented on helm/config/nginx.mapproxy.conf
> +uwsgi_param HTTP_X_SCRIPT_NAME {{ .Values.mapproxy.route.path }};
added ternary condition to support route or ingress

2023-09-06 07:38 UTC, vitaligi commented on requirements.txt
> +protobuf==3.17.3
added redis for cache support

2023-09-06 12:52 UTC, vitaligi commented on Dockerfile
> +    TELEMETRY_TRACING_ENABLED='true' \
tested it with compose, should work with helm as well. this was not something I've changed

2023-09-06 13:05 UTC, vitaligi commented on Dockerfile
> +    TELEMETRY_SAMPLING_RATIO_DENOMINATOR=1000
again, not something new that was introduced, but yes it should be added and will be

2023-09-06 13:14 UTC, vitaligi commented on config/mapproxy/metrics.py
> +        if environ['PATH_INFO'] == '/metrics':
not something existing
there are dashboards for uwsgi - https://grafana.com/grafana/dashboards/?search=wsgi

2023-09-06 15:16 UTC, vitaligi commented on config/mapproxy/app.py
> +application = Metrics(application)
changed

2023-09-06 15:34 UTC, vitaligi commented on config/nginx/nginx.default.conf
> +log_format json_format escape=json '{"timestamp": $time_iso8601, "source": "nginx", "status": $status, "method": "$request_method", "uri": "$request_uri", "user_agent": "$http_user_agent", "resp_time
no, should we?

2023-09-06 15:44 UTC, vitaligi commented on docker-compose.yml
> +      # - TELEMETRY_SAMPLING_RATIO_DENOMINATOR=1
added

2023-09-06 16:51 UTC, vitaligi commented on helm/templates/mapproxy-configmap.yaml
> +  AUTH_ENABLED: {{ .Values.mapproxy.env.authentication.WMS.enabled | quote }}
it was decided to remove it auth AFAIK

2023-09-07 12:08 UTC, vitaligi commented on helm/templates/mapproxy-configmap.yaml
> +  TELEMETRY_TRACING_ENABLED: {{ .Values.global.tracing.enabled | quote }}
added both

2023-09-13 12:14 UTC, vitaligi commented
currently there is a missing uwsgi exporter container missing chart, wip

2023-09-18 14:02 UTC, CL-SHLOMIKONCHA submitted a review, later dismissed

2023-09-20 11:19 UTC, asafMasa commented on helm/templates/mapproxy-configmap.yaml
>    AUTH_VALID_DOMAIN: {{ .Values.mapproxy.env.authentication.WMS.requiredDomain | quote }}
remove wms

2023-09-20 11:24 UTC, vitaligi commented on Dockerfile
> +    TELEMETRY_METRICS_ENABLED='false' \
removing duplicates

2023-09-20 12:53 UTC, CL-SHLOMIKONCHA approved these changes

2023-09-20 12:54 UTC, merged