feat: added support for envoy auth
MapColonies/mapproxy pull request #14
Opened 2024-02-18 08:08 UTC by CL-SHLOMIKONCHA

2024-02-21 12:26 UTC, asafMasa requested changes

2024-02-21 12:26 UTC, asafMasa commented on helm/templates/mapproxy/mapproxy-container.yaml
> +                name:  {{ $configmapName }}
space?

2024-02-21 12:26 UTC, asafMasa commented on helm/values.yaml
> +    enabled: false
please check uwsgiExporter metrics are collected

2024-02-21 13:33 UTC, CL-SHLOMIKONCHA commented on helm/config/mapProxyUwsgi.ini
> +{{ if .Values.mapproxy.env.metrics.enabled }}
fix

2024-02-21 13:34 UTC, CL-SHLOMIKONCHA commented on helm/config/log.ini
> +[loggers]
talked with vitali, reverted to log.yaml.

2024-02-21 13:34 UTC, CL-SHLOMIKONCHA commented on helm/config/default.conf
> +    {{ end }}
fix

2024-02-21 13:34 UTC, CL-SHLOMIKONCHA commented on helm/config/mapProxyUwsgi.ini
> +master-fifo = /uwsgi_config/fifo0
fix

2024-02-21 13:35 UTC, CL-SHLOMIKONCHA commented on helm/config/nginx.conf
> +    {{ end}}
fix

2024-02-21 13:35 UTC, CL-SHLOMIKONCHA commented on helm/Chart.yaml
> +version: 2.0.0
fixed

2024-02-21 13:39 UTC, CL-SHLOMIKONCHA commented on helm/templates/_resources.tpl
> +{{- define "ingress.fullname" -}}
this definition and route removed because nginx is manages it

2024-02-21 13:39 UTC, CL-SHLOMIKONCHA commented on helm/templates/mapproxy/mapproxy-container.yaml
> +                name:  {{ $configmapName }}
fixed

2024-02-21 13:44 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +metrics:
in-use now

2024-02-21 13:50 UTC, CL-SHLOMIKONCHA commented on helm/templates/_resources.tpl
> +{{- define "ingress.fullname" -}}
added domain

2024-02-21 14:10 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    enabled: false
done

2024-02-22 09:21 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    url: ""
created an issue [MAPCO-4021](https://mapcolonies.atlassian.net/browse/MAPCO-4021)

2024-02-22 10:20 UTC, asafMasa requested changes
Good job!

2024-02-22 10:20 UTC, asafMasa commented on config/scripts/docker-entrypoint.sh
> +    cp -f /mapproxy/log.ini /mapproxy/settings/log.ini
shouldn't it be reverted?

2024-02-22 10:20 UTC, asafMasa commented on config/scripts/docker-entrypoint.sh
> +if [[ ! -f /mapproxy/log.ini ]]; then
shouldn't it be reverted?

2024-02-22 10:20 UTC, asafMasa commented on config/app/app.py
> +from os import path
why do you need it?

2024-02-22 10:20 UTC, asafMasa commented on helm/config/log.yaml
> +    handlers: [source_requests]
revert

2024-02-22 10:20 UTC, asafMasa commented on .github/workflows/build_and_push.yaml
> +        working-directory: ./helm
end of file

2024-02-22 10:20 UTC, asafMasa commented on helm/values.yaml
> +  fullnameOverride: mapproxy-test-mapproxy-nginx
empty?

2024-02-22 10:26 UTC, CL-SHLOMIKONCHA commented on config/scripts/docker-entrypoint.sh
> +if [[ ! -f /mapproxy/log.ini ]]; then
yup, reverted

2024-02-22 10:26 UTC, CL-SHLOMIKONCHA commented on config/app/app.py
> +from os import path
removed

2024-02-22 10:27 UTC, CL-SHLOMIKONCHA commented on helm/config/log.yaml
> +    handlers: [source_requests]
fixed

2024-02-22 10:28 UTC, CL-SHLOMIKONCHA commented on config/scripts/docker-entrypoint.sh
> +    cp -f /mapproxy/log.ini /mapproxy/settings/log.ini
yup, reverted

2024-02-22 10:29 UTC, CL-SHLOMIKONCHA commented on .github/workflows/build_and_push.yaml
> +        working-directory: ./helm
fixed

2024-02-22 10:30 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  fullnameOverride: mapproxy-test-mapproxy-nginx
fixed

2024-02-22 14:09 UTC, merged