chore: implement infra nginx. (MAPCO-3391)
MapColonies/mapproxy pull request #3
Opened 2023-09-28 12:11 UTC by almog8k

2023-10-08 12:32 UTC, asafMasa requested changes
Good job

2023-10-08 12:32 UTC, asafMasa commented on helm/config/nginx.conf
> +            '"ssl_client_serial": "$ssl_client_serial",'
remove ssl logs

2023-10-08 12:32 UTC, asafMasa commented on helm/templates/configmap-nginx.yaml
> +{{- end }}
add end of file space

2023-10-08 12:32 UTC, asafMasa commented on helm/templates/mapproxinator-container.yaml
> +            {{- end }}
revert space

2023-10-08 12:32 UTC, asafMasa commented on helm/templates/mapproxy-bundle.yaml
> +        {{- end }}
revert space

2023-10-08 12:32 UTC, asafMasa commented on helm/templates/mapproxy-init-container.yaml
> +            {{- end }}
revert space

2023-10-08 12:32 UTC, asafMasa commented on helm/templates/mapproxy-init-container.yaml
> +            {{- end }}
revert spaces

2023-10-09 06:43 UTC, CL-SHLOMIKONCHA commented on helm/config/default.conf
> +map $msec $nanosec {
as i know the opa-la repo we override this nginx config file by 'extraVolumeMounts', in that case it is necessary

2023-10-09 06:46 UTC, CL-SHLOMIKONCHA commented on helm/config/nginx.conf
> +            '"ssl_client_serial": "$ssl_client_serial",'
removed all SSL logs

2023-10-09 06:48 UTC, CL-SHLOMIKONCHA commented on helm/templates/mapproxy-bundle.yaml
> +        {{- end }}
fixed

2023-10-09 06:48 UTC, CL-SHLOMIKONCHA commented on helm/templates/mapproxinator-container.yaml
> +            {{- end }}
fixed

2023-10-09 06:49 UTC, CL-SHLOMIKONCHA commented on helm/templates/mapproxy-init-container.yaml
> +            {{- end }}
fixed

2023-10-09 06:49 UTC, CL-SHLOMIKONCHA commented on helm/templates/mapproxy-init-container.yaml
> +            {{- end }}
fixed

2023-10-09 07:37 UTC, CL-SHLOMIKONCHA commented on helm/templates/configmap-nginx.yaml
> +{{- end }}
fixed

2023-10-09 07:45 UTC, asafMasa approved these changes

2023-10-09 08:21 UTC, merged